### ISSUE TITLE
I have a quick close issue. Not anyone encountered this?

### ISSUE THREAD

**Issue by talhazengin** [lextm/windowsterminal-shell#16]
Script ran successfully but when i click to open as administrator or normally, terminal window will opening and closing quickly.

**Comment by lextm** [comment]
When you click any "as administrator" menu item, two windows are opened. One of them should close immediately itself, while the other remains and is the elevated Windows terminal for you to use.

If your observation matches this, then that's normal and by design (elevation as administrator requires the first window).

If you observed something different, can you capture a short video to reveal what you saw?

**Comment by talhazengin** [comment]
I uploaded the problem.
[problem.zip](https://github.com/lextm/windowsterminal-shell/files/4682920/problem.zip)

**Comment by lextm** [comment]
Thanks. That's clear.

1. When "as administrator" items are clicked, we do see the first PowerShell window flash as expected. That indicates the menu items were created properly.
2. No Windows Terminal window is showed, no matter which menu item you clicked. That indicates wt.exe does not work on your machine.

Can you open command prompt and run the following?
```
%localappdata%\Microsoft\WindowsApps\wt.exe -d .
```
What happens when this executes will tell us more about the culprit.

**Comment by talhazengin** [comment]
wt.exe is in the right place, it is not the problem.

I think the problem is spaces in the user profile folder path.

This not recognized:
%localappdata%\Microsoft\WindowsApps\wt.exe -d .

But this is working (with single quotation marks):
"%localappdata%\Microsoft\WindowsApps\wt.exe" -d .

My local appdata folder;
C:\Users\Talha Zengin\AppData\Local

As you can see there is spaces in the path. Problem is this.

**Comment by lextm** [comment]
You can now try the latest version. By using another approach to launch Windows Terminal I think this issue is resolved.
